### ISSUE TITLE
departure/arrival times show 3 minutes ahead of gtfs time

### ISSUE THREAD

**Issue by yipcma** [hove-io/navitia#1972] opened 2017-02-08 18:41 UTC
I'm totally in the dark for this, i hand-verify that the formats in the gtfs stop_times is fine, yet all arrivals departures returned by the api call gives 3 minutes ahead... super strange.

**Comment by pbougue** [comment] 2017-02-08 19:49
This may also be linked to https://github.com/CanalTP/navitia/issues/1968 as before the correction (so until now as we did not deliver a new version yet) the problem was that for TimeZones without DST, we shifted in minutes instead of hours (so if you're in UTC+3 this might be the cause).
To test if this will be solved by this fix, you can switch your data (in agency.txt) to `Europe/Paris` and see if times are correct (for Paris of course).

Otherwise, we would need more informations... Maybe on IRC if someone is around. And maybe a sample of data to reproduce the bug.

**Comment by yipcma** [comment] 2017-02-09 11:00
sure thing. I'll communicate on IRC then for this one :) right now i just patch it by adding 3 hours when query and adding 3 minutes when displaying the result. which serves the purpose
.

**Comment by pbougue** [comment] 2017-02-09 14:37
Ok, this really looks like it's the same problem, if you have time to test another timezone (with DST), let us know the outcome!

**Comment by pbougue** [comment] 2017-02-27 15:53
This should have been fixed by https://github.com/CanalTP/navitia/pull/1969
I close this issue, feel free to update it if something new comes up (considering that navitia/debian8_simple is outdated, thus the fix is not deployed in it. Consider using https://github.com/CanalTP/navitia-docker-compose instead).

**Closed as completed by pbougue** 2017-02-27 15:53 UTC
